version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: ethiopet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethiopet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: ethiopet-redis
    ports:
      - '6379:6379'
volumes:
  pgdata:
